### ISSUE TITLE
Error occurs when I run command "cargo install -f wasm-bindgen@0.2.29"

### ISSUE THREAD

**Issue by huangkaizh** [chinedufn/webgl-water-tutorial#3]
It said:
 could not find `wasm-bindgen@0.2.29` in registry `https://github.com/rust-lang/crates.io-index`
I am new to rust, don't know why this happened.

**Comment by chinedufn** [comment]
Hmmm what happens if you try wasm-bindgen@0.2.30 ?

**Comment by chinedufn** [comment]
Ahhh sorry it should be wasm-bindgen-cli@0.2.29
