### ISSUE TITLE
build.sh fails

### ISSUE THREAD

**Issue by darkoverlordofdata** [chinedufn/webgl-water-tutorial#4]
I'm using rustc 1.38.0 (625451e37 2019-09-23) on Debian Buster.
Log:

darkoverlordofdata@penguin:~/Documents/GitHub/webgl-water-tutorial$ ./build.sh
   Compiling proc-macro2 v1.0.5
   Compiling unicode-xid v0.2.0
   Compiling proc-macro2 v0.4.30
   Compiling autocfg v0.1.6
   Compiling syn v1.0.5
   Compiling cc v1.0.46
   Compiling unicode-xid v0.1.0
   Compiling libc v0.2.65
   Compiling syn v0.15.44
   Compiling memchr v2.2.1
   Compiling serde v1.0.101
   Compiling log v0.4.8
   Compiling wasm-bindgen-shared v0.2.29
   Compiling version_check v0.1.5
   Compiling typenum v1.11.2
   Compiling failure_derive v0.1.6
   Compiling cfg-if v0.1.10
   Compiling libm v0.1.4
   Compiling rand_core v0.4.2
   Compiling matrixmultiply v0.1.15
   Compiling ryu v1.0.2
   Compiling bitflags v1.2.1
   Compiling rustc-demangle v0.1.16
   Compiling lazy_static v1.4.0
   Compiling unicode-segmentation v1.3.0
   Compiling byteorder v1.3.2
   Compiling rawpointer v0.1.0
   Compiling quick-error v1.2.2
   Compiling regex-syntax v0.6.12
   Compiling unicode-width v0.1.6
   Compiling ansi_term v0.11.0
   Compiling termcolor v1.0.5
   Compiling vec_map v0.8.1
   Compiling wasm-bindgen v0.2.29
   Compiling itoa v0.4.4
   Compiling yaml-rust v0.3.5
   Compiling strsim v0.8.0
   Compiling sourcefile v0.1.4
   Compiling num-traits v0.2.8
   Compiling num-complex v0.2.3
   Compiling backtrace-sys v0.1.32
   Compiling nom v4.2.3
   Compiling rand_core v0.3.1
   Compiling thread_local v0.3.6
   Compiling heck v0.3.1
   Compiling humantime v1.3.0
   Compiling textwrap v0.11.0
   Compiling rand v0.5.6
   Compiling quote v1.0.2
   Compiling quote v0.6.13
   Compiling atty v0.2.13
   Compiling aho-corasick v0.7.6
   Compiling generic-array v0.11.1
   Compiling serde_json v1.0.41
   Compiling bincode v1.0.1
   Compiling approx v0.3.2
   Compiling backtrace v0.3.40
   Compiling clap v2.33.0
   Compiling regex v1.3.1
   Compiling weedle v0.8.0
   Compiling synstructure v0.12.1
   Compiling serde_derive v1.0.101
   Compiling wasm-bindgen-backend v0.2.29
   Compiling alga v0.7.2
   Compiling landon v0.1.2
   Compiling env_logger v0.6.2
   Compiling wasm-bindgen-macro-support v0.2.29
   Compiling nalgebra v0.16.12
warning[E0502]: cannot borrow `*self` as immutable because it is also borrowed as mutable
   --> /home/darkoverlordofdata/.cargo/registry/src/github.com-1ecc6299db9ec823/nalgebra-0.16.12/src/base/cg.rs:291:44
    |
291 |                 self[(j, i)] += shift[j] * self[(D::dim() - 1, i)];
    |                 ---------------------------^^^^-------------------
    |                 |                          |
    |                 |                          immutable borrow occurs here
    |                 mutable borrow occurs here
    |                 mutable borrow later used here
    |
    = warning: this error has been downgraded to a warning for backwards compatibility with previous releases
    = warning: this represents potential undefined behavior in your code and this warning will become a hard error in the future
    = note: for more information, try `rustc --explain E0729`

warning[E0502]: cannot borrow `*self` as immutable because it is also borrowed as mutable
   --> /home/darkoverlordofdata/.cargo/registry/src/github.com-1ecc6299db9ec823/nalgebra-0.16.12/src/base/cg.rs:291:44
    |
291 |                 self[(j, i)] += shift[j] * self[(D::dim() - 1, i)];
    |                 ---------------------------^^^^-------------------
    |                 |                          |
    |                 |                          immutable borrow occurs here
    |                 mutable borrow occurs here
    |                 mutable borrow later used here
    |
    = warning: this error has been downgraded to a warning for backwards compatibility with previous releases
    = warning: this represents potential undefined behavior in your code and this warning will become a hard error in the future
    = note: for more information, try `rustc --explain E0729`

   Compiling failure v0.1.6
   Compiling wasm-bindgen-macro v0.2.29
   Compiling wasm-bindgen-webidl v0.2.23
   Compiling blender-mesh v0.3.3
   Compiling blender-armature v0.1.7
   Compiling web-sys v0.3.6
   Compiling webgl-water-tutorial v0.1.0 (/home/darkoverlordofdata/Documents/GitHub/webgl-water-tutorial)
   Compiling js-sys v0.3.6
   Compiling console_error_panic_hook v0.1.5
error: failed to run custom build command for `webgl-water-tutorial v0.1.0 (/home/darkoverlordofdata/Documents/GitHub/webgl-water-tutorial)`

Caused by:
  process didn't exit successfully: `/home/darkoverlordofdata/Documents/GitHub/webgl-water-tutorial/target/debug/build/webgl-water-tutorial-9e3ae92ddecf2748/build-script-build` (exit code: 101)
--- stdout
cargo:rerun-if-changed=./terrain.blend
cargo:rerun-if-changed=./bird.blend

--- stderr
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/libcore/result.rs:1084:5
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.34/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.34/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:47
   3: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:36
   4: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:200
   5: std::panicking::default_hook
             at src/libstd/panicking.rs:214
   6: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:477
   7: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:384
   8: rust_begin_unwind
             at src/libstd/panicking.rs:311
   9: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
  10: core::result::unwrap_failed
             at src/libcore/result.rs:1084
  11: core::result::Result<T,E>::unwrap
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/libcore/result.rs:852
  12: build_script_build::main
             at ./build.rs:33
  13: std::rt::lang_start::{{closure}}
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/libstd/rt.rs:64
  14: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:49
  15: std::panicking::try::do_call
             at src/libstd/panicking.rs:296
  16: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:80
  17: std::panicking::try
             at src/libstd/panicking.rs:275
  18: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  19: std::rt::lang_start_internal
             at src/libstd/rt.rs:48
  20: std::rt::lang_start
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/libstd/rt.rs:64
  21: main
  22: __libc_start_main
  23: _start
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: failed to read `./target/wasm32-unknown-unknown/debug/webgl_water_tutorial.wasm`
    caused by: No such file or directory (os error 2)
darkoverlordofdata@penguin:~/Documents/GitHub/webgl-water-tutorial$

**Comment by chinedufn** [comment]
Ahh maybe debian doesn't have the `command` binary.

If you type `which command` in your shell is there no output?

Regardless you can fix this by  commenting out the entire build script `main.rs` contents - or by installing Blender and adding it to your `$PATH`

**Comment by darkoverlordofdata** [comment]
I installed blender. But now I get this error:

error[E0554]: #![feature] may not be used on the stable release channel 

Oh well. I'm giving up on rust anyway, it seems my computer doesn't have enough ram to use rucstc - everytime I compile something larger than hello world, my computer freezes up - I'll stick with c++ :)

**Comment by chinedufn** [comment]
`rustup default nightly` should do the trick

Sorry to see you go - hopefully you try Rust again in the future!
