### ISSUE TITLE
build.sh to install required components, and build without overriding toolchain.

### ISSUE THREAD

**Issue by Ben-PH** [chinedufn/webgl-water-tutorial#6]
Rather than having to change the environment with `rustup override set nightly-...`, you can use `cargo  +nightly-... build` and it will change to that setting for that build run, assuming it's installed. 

You can do this in ./build.sh rather trivially if you don't intend for any cli options. I'd be happy do a PR for something like that. I'll also add things like installing the right nightly toolchain and wasm-bindgen-cli, assuming that it's straight forward.

**Comment by chinedufn** [comment]
@Ben-PH that would be awesome if you PR'd that - thanks!

I think that people should be able to run the build script multiple times and not have to download wasm-bindgen-cli each time - so as long as that's still possible any improvement that you have in mind works for me!

**Comment by berdon** [comment]
Any chance for this PR @Ben-PH ?

**Comment by berdon** [comment]
See https://github.com/chinedufn/webgl-water-tutorial/pull/9

**Comment by chinedufn** [comment]
Closed via https://github.com/chinedufn/webgl-water-tutorial/pull/9

Thanks @berdon for the nifty contribution.
