### ISSUE TITLE
Build fails on Cargo.lock content, followed by stability issues

### ISSUE THREAD

**Issue by Ben-PH** [chinedufn/webgl-water-tutorial#7]
When I try building according to the readme, i get the following error:
```
error: failed to parse lock file at: /home/ben/langs/wasm-rust/webgl-water-tutorial/Cargo.lock

Caused by:
  invalid serialized PackageId for key `package.dependencies`
```

On removing Cargo.lock, I had trouble building nalgebra (0.16.12), which had some errors

I went into the Cargo.toml file, and updated to latest nalgebra (0.21.0), and seemed to compile fine, but version 0.16.12 still wanted to compile, with the same failures. I changed `web_sys` to the latest version, removed .lock again, cleaned and recompiled to get a good build.

Instead of nalgebra 0.16.12 building, it was 0.16.14. This still failed on todays nightly.

(FINALLY), when I commented out the #![feature(custom_attribute)], it worked, and got it running on chromium.

I'll fork and add a PR to sort all that out, and clear up the warnings while I'm at it.

**Comment by chinedufn** [comment]
Awesome - thanks so much for exploring this!

**Comment by chinedufn** [comment]
I think #9 should address this, but feel free to re-open if not. Thanks so much for the detailed issue.
