### ISSUE TITLE
Failed: cargo install -f wasm-bindgen-cli --version 0.2.29 

### ISSUE THREAD

**Issue by vladbuich** [chinedufn/webgl-water-tutorial#8]
Following the installation described in readme, build failed after running this command
> cargo install -f wasm-bindgen-cli --version 0.2.29

<img width="996" alt="Снимок экрана 2020-07-06 в 12 41 13" src="https://user-images.githubusercontent.com/24589835/86568222-fb8b7e00-bf85-11ea-87fc-8effdc396137.png">

**Comment by chinedufn** [comment]
Hmmm, can you try

```
rustup update stable && rustup default stable
```

And if that does not make it work ...

```
rustup update nightly && rustup default nightly
```

(_I forget whether or not wasm-bindgen-cli needs nightly_)

**Comment by vladbuich** [comment]
@chinedufn thanks for your response. Unfortunately, it didn't help

**Comment by chinedufn** [comment]
Ah gotcha. I think the issue is that this tutorial was written against an older version of the Rust tools.

I've changed the order of setup instructions -> https://github.com/chinedufn/webgl-water-tutorial/commit/c5f214f4d08337ca74c130324a125d035efd9f7a

Can you try again by following these modified instructions?

```
# You can use any static file server that properly sets the
# `application/wasm` mime type
npm install -g http-server

git clone https://github.com/chinedufn/webgl-water-tutorial
cd webgl-water-tutorial

# A version of Rust from around the time the tutorial was written.
rustup override set nightly-2019-01-06
rustup target add wasm32-unknown-unknown

cargo install -f wasm-bindgen-cli --version 0.2.29 # Or download a release binary
./build.sh

## Opens your browser to http://localhost:8080  where the demo will be running
http-server --open
```

**Comment by vladbuich** [comment]
failed again after:

> cargo install -f wasm-bindgen-cli --version 0.2.29

but there are some new errors

<img width="653" alt="Снимок экрана 2020-07-07 в 17 06 59" src="https://user-images.githubusercontent.com/24589835/86778835-471c5580-c074-11ea-88a6-0c6ea3118479.png">

**Comment by chinedufn** [comment]
Hmm.. Can you `rustc -V && cargo -V`

Then I can take a look and try to reproduce the issue.

**Comment by vladbuich** [comment]
> rustc -V && cargo -V
rustc 1.33.0-nightly (68fe5182c 2019-01-05)
cargo 1.33.0-nightly (34320d212 2019-01-03)

**Comment by chinedufn** [comment]
Can you `rm Cargo.lock` and try again

**Comment by vladbuich** [comment]
Sorry that not answering for so long, but it didn't help again..
I cloned fresh version of the project and followed each command in readme

<img width="998" alt="Снимок экрана 2020-07-17 в 15 25 19" src="https://user-images.githubusercontent.com/24589835/87776777-bac31d00-c841-11ea-965c-0e7571fafd56.png">

**Comment by chinedufn** [comment]
I verified that this works. The README has been updated with the following:

```
# You can use any static file server that properly sets the
# `application/wasm` mime type
npm install -g http-server

git clone https://github.com/chinedufn/webgl-water-tutorial
cd webgl-water-tutorial

# A version of Rust that can compile wasm-bindgeen-cli version 0.2.29
rustup override set nightly-2020-06-22
cargo install -f wasm-bindgen-cli --version 0.2.29 # Or download a release binary

# A version of Rust from around the time the tutorial was written.
rustup override set nightly-2019-01-06
rustup target add wasm32-unknown-unknown

./build.sh

## Opens your browser to http://localhost:8080  where the demo will be running
http-server --open
```

Let me know if you have any issues!
